apiVersion: v1
kind: Pod
metadata:
  name: tomcat
  containers:
    - image: tomcat:tomcat
      name: tomcat
      command: ["sh", "-c", "/root/apache-tomcat-7.0.42-v2/bin/start.sh"]      
      ports:
        - containerPort: 8080
          hostPort: 8001  
      #https://github.com/kubernetes/examples/tree/master/staging/javaweb-tomcat-sidecar
