apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: tomcat
spec:
  containers:
  - name: tomcat
    image: tomcat:tomcat
    ports:
    - containerPort: 8080
    #  imagePullPolicy: Always
      #command: ["sh", "-c", "/root/apache-tomcat-7.0.42-v2/bin/start.sh"]      
      #ports:
#containerPort: 8080
      #imagePullPolicy: Always
      #https://github.com/kubernetes/examples/tree/master/staging/javaweb-tomcat-sidecar
